version: '3.8'

services:
  mysql:
    image: mysql
    container_name: hr_mysql
    env_file: webapp_env
    ports:
      - "3308:3306"
    volumes:
      - hr-mysql-data:/var/lib/mysql
    restart: always
    

volumes:
  hr-mysql-data: